from dielectric_functions import *
from epsilon_routines import *
from epsilon_helper import *
from numba import njit, jit
import numba as nb

cell, dark_objects = initialize_cell()
dark_objects = dielectric_RPA(cell, dark_objects)
q = list(dark_objects['unique_q'].keys())[0]

ivalbot, ivaltop, iconbot, icontop = np.load(parmt.store + '/bands.npy')
dft_path = parmt.store + '/DFT/'
mo_coeff_i = np.load(dft_path + 'mo_coeff_i.npy')[:,:,ivalbot:ivaltop+1]
mo_coeff_f = np.load(dft_path + 'mo_coeff_f.npy')[:,:,iconbot:icontop+1]
mo_en_i = np.load(dft_path + 'mo_en_i.npy')[:,ivalbot:ivaltop+1]
mo_en_f = np.load(dft_path + 'mo_en_f.npy')[:,iconbot:icontop+1]
k_f = np.load(parmt.store + '/k-pts_f.npy')

unique_q = dark_objects['unique_q']
n_q = len(unique_q) #number of 1BZ q vectors
G_vectors = dark_objects['G_vectors']
R_vectors = dark_objects['R_vectors']
N_AO = len(dark_objects['aos'])
blocks = dark_objects['blocks']
V_cell = dark_objects['V_cell']
q_cuts = dark_objects['R_cutoff_q_points']

unique_Ri = load_unique_R()

#energy bins
E = np.arange(0, parmt.E_max+parmt.dE, parmt.dE)

k_pairs = np.array(unique_q[q])
N_kpairs = k_pairs.shape[0]

#Only include G_vectors such that |q + G| < q_max
q = np.array(q)
G_q = G_vectors[np.linalg.norm(q+G_vectors, axis=1) < parmt.q_max]

#generate parameters for q
mo_en_i_q = mo_en_i[k_pairs[:,0]] #(k_pair,i)
mo_en_f_q = mo_en_f[k_pairs[:,1]] #(k_pair,j)
mo_coeff_i_q = mo_coeff_i[k_pairs[:,0]] #(k_pair,a,i)
mo_coeff_f_q_conj = mo_coeff_f[k_pairs[:,1]].conj() #(k_pair,b,j)
k_f_q = k_f[k_pairs[:,1]]

#Compute and store energy differences for denominator of Re(chi), and Im(chi)
get_energy_diff(mo_en_i_q, mo_en_f_q, E)

qG = q
R_id = np.load(parmt.store + '/R_ids/{}.npy'.format(np.sum(q_cuts < np.linalg.norm(qG)) - 1))

def load_ints(qG, unique_Ri, k_f):
    ints = []
    for d in range(3): #435us total
        ints.append(np.load(parmt.store + '/primgauss_1d_integrals/dim_{}/{:.5f}.npy'.format(d, qG[d]))[:,None,:,:] * np.exp(-1.j*unique_Ri[d][:,None]*k_f[None,:,d])[:,:,None,None])
    return ints

ints = load_ints(qG, unique_Ri, k_f_q)

BlockDict = nb.types.DictType(nb.types.Tuple(nb.int32))

@jit(nopython=False)
def get_3D_overlaps_blocks_jit(qG:np.ndarray, k_f:np.ndarray, blocks:dict, N_AO:int, mo_coeff_i:np.ndarray, mo_coeff_f_conj:np.ndarray, R_id, ints) -> np.ndarray:
    """
    Calculates all 3D overlaps eta = <jk'|exp(i(q+G)r)|ik> for a given 1BZ q-vector and given G-vector using stored 1D overlaps

    Inputs:
        qG:             np.ndarray of shape (3,): q+G
        k_f:            np.ndarray of shape (N_kpairs, 3): k' corresponding to q
        blocks:         dict: atomic orbital blocks generated by get_basis_blocks 
        N_AO:           int: number of atomic orbitals
        mo_coeff_i:     np.ndarray of shape (N_kpairs, N_AO, N_valbands)
        mo_coeff_f:     np.ndarray of shape (N_kpairs, N_AO, N_conbands)
        unique_Ri:      list of [R_unique_x, R_unique_y, R_unique_z)
        q_cuts:         np.ndarray of shape (N_q, ): |q+G| at which R_cutoff change
    Outputs:
        eta_qG:         np.ndarray of shape (N_kpairs, N_val_bands (i), N_cond_bands (j)): all 3D overlaps <jk'|exp(i(q+G)r)|ik>
    """
    """
    R_id = np.load(parmt.store + '/R_ids/{}.npy'.format(np.sum(q_cuts < np.linalg.norm(qG)) - 1))
    ints = []
    for d in range(3): #435us total
        ints.append(np.load(parmt.store + '/primgauss_1d_integrals/dim_{}/{:.5f}.npy'.format(d, qG[d]))[:,None,:,:] * np.exp(-1.j*unique_Ri[d][:,None]*k_f[None,:,d])[:,:,None,None])
    """
    ovlp = np.empty((k_f.shape[0], N_AO, N_AO), dtype = np.complex128) 
    for p1 in list(blocks.keys()):
        d1 = blocks[p1]
        p1 = np.array(p1)
        ints_i = []
        for d in range(3):
            ints_i.append(ints[d][:,:,:,p1[d]])
        for p2 in list(blocks.keys()):
            d2 = blocks[p2]
            p2 = np.array(p2)
            tot = np.ones((R_id.shape[1], k_f.shape[0], p2.shape[1], p1.shape[1]), dtype = np.complex128)
            for d in range(3):
                ints_ij = ints_i[d][:,:,p2[d]]
                tot *= ints_ij[R_id[d]]
            tot = tot.sum(axis = 0)
            for i in d1:
                for j in d2:
                    ovlp[:,i,j] = (tot@d1[i])@d2[j]
    return np.einsum('kbj,kba,kai->kij', mo_coeff_f_conj, ovlp, mo_coeff_i, optimize = True)