import numpy as np
from numba import njit

import dielectric_pyscf.input_parameters as parmt

#Constants
alpha = 1/137
me = 0.51099895000e6 #eV

def get_3D_overlaps_blocks(qG:np.ndarray, k_f:np.ndarray, blocks:dict, N_AO:int, mo_coeff_i:np.ndarray, mo_coeff_f_conj:np.ndarray, unique_Ri:list[np.ndarray], q_cuts:np.ndarray) -> np.ndarray:
    """
    Calculates all 3D overlaps eta = <jk'|exp(i(q+G)r)|ik> for a given 1BZ q-vector and given G-vector using stored 1D overlaps

    Inputs:
        qG:             np.ndarray of shape (3,): q+G
        k_f:            np.ndarray of shape (N_kpairs, 3): k' corresponding to q
        blocks:         dict: atomic orbital blocks generated by get_basis_blocks 
        N_AO:           int: number of atomic orbitals
        mo_coeff_i:     np.ndarray of shape (N_kpairs, N_AO, N_valbands)
        mo_coeff_f:     np.ndarray of shape (N_kpairs, N_AO, N_conbands)
        unique_Ri:      list of [R_unique_x, R_unique_y, R_unique_z)
        q_cuts:         np.ndarray of shape (N_q, ): |q+G| at which R_cutoff change
    Outputs:
        eta_qG:         np.ndarray of shape (N_kpairs, N_val_bands (i), N_cond_bands (j)): all 3D overlaps <jk'|exp(i(q+G)r)|ik>
    """
    R_id = np.load(parmt.store + '/R_ids/{}.npy'.format(np.sum(q_cuts < np.linalg.norm(qG)) - 1))
    ints = []
    for d in range(3): #435us total
        ints.append(np.load(parmt.store + '/primgauss_1d_integrals/dim_{}/{:.5f}.npy'.format(d, qG[d]))[:,None,:,:] * np.exp(-1.j*unique_Ri[d][:,None]*k_f[None,:,d])[:,:,None,None])
    ovlp = np.empty((k_f.shape[0], N_AO, N_AO), dtype = np.complex128) 
    for p1 in blocks:
        d1 = blocks[p1]
        p1 = np.array(p1)
        ints_i = []
        for d in range(3):
            ints_i.append(ints[d][:,:,:,p1[d]])
        for p2 in blocks:
            d2 = blocks[p2]
            p2 = np.array(p2)
            tot = np.ones((R_id.shape[1], k_f.shape[0], p2.shape[1], p1.shape[1]), dtype = np.complex128)
            for d in range(3):
                ints_ij = ints_i[d][:,:,p2[d]]
                tot *= ints_ij[R_id[d]]
            tot = tot.sum(axis = 0)
            for i in d1:
                for j in d2:
                    ovlp[:,i,j] = (tot@d1[i])@d2[j]
    return np.einsum('kbj,kba,kai->kij', mo_coeff_f_conj, ovlp, mo_coeff_i, optimize = True)

def RPA_Im_eps_external_prefactor_no_LFE(qG, blocks, N_AO, q_cuts, unique_Ri):
    """
    Returns |<j(k+q)|exp(i(q+G)r)|ik>|^2/|q+G|^2 summed over i,j,k

    Notes:
        -Speed up with numba? Is saving+loading data and using for loops or keeping data in memory and optimizing for loops with numba faster?

    Inputs: 
        qG:         np.ndarray, ndim = 1, shape = (3, ), q+G vector
        blocks:     dict, atomic orbital blocks generated by get_basis_blocks
        N_AO:       int, number of atomic orbitals
        q_cuts:     np.ndarray, cut-off points in q for different R_ids.
    Outputs:
        im_eps:     Imaginary part of RPA dielectric function, no LFE, 
                    shape = (int(parmt.E_max/parmt.dE + 1), ), prefactor multiplied later.
    """
    # Load data
    working_dir = parmt.store + '/working_dir/'
    energy_arr = np.load(working_dir + 'im_energy.npy')
    k_f = np.load(working_dir + 'k_f.npy')
    mo_coeff_f_conj = np.load(working_dir + 'mo_coeff_f_conj.npy')
    mo_coeff_i = np.load(working_dir + 'mo_coeff_i.npy')

    nk = len(energy_arr)
    nE = int(parmt.E_max/parmt.dE + 1)
    im_eps = np.zeros(int(parmt.E_max/parmt.dE + 1))
    if nk > 16:
        partitions = np.append(np.arange(0, nk, 16), [nk])
        for p in range(len(partitions) - 1):
            i, f = partitions[p], partitions[p+1]
            eta_qG = get_3D_overlaps_blocks(qG, k_f[i:f], blocks, N_AO, mo_coeff_i[i:f], mo_coeff_f_conj[i:f], unique_Ri, q_cuts)
            eta_qG_sq = (eta_qG*eta_qG.conj()).real
            del eta_qG
            for k in range(i, f):
                for a in range(mo_coeff_i.shape[2]):
                    for b in range(mo_coeff_f_conj.shape[2]):
                        ind, rem = tuple(energy_arr[k, a, b])
                        if ind < nE:
                            im_eps[int(ind)] += rem*eta_qG_sq[k - i, a, b]
                        if ind < nE - 1:
                            im_eps[int(ind+1)] += (1. - rem)*eta_qG_sq[k - i, a, b]
    else:
        eta_qG = get_3D_overlaps_blocks(qG, k_f, blocks, N_AO, mo_coeff_i, mo_coeff_f_conj, unique_Ri, q_cuts)
        eta_qG_sq = (eta_qG*eta_qG.conj()).real
        del eta_qG
        for k in range(nk):
            for a in range(mo_coeff_i.shape[1]):
                for b in range(mo_coeff_f_conj.shape[1]):
                    ind, rem = tuple(energy_arr[k, a, b])
                    if ind < nE:
                        im_eps[int(ind)] += rem*eta_qG_sq[k, a, b]
                    if ind < nE - 1:
                        im_eps[int(ind+1)] += (1. - rem)*eta_qG_sq[k, a, b]
    return im_eps/(qG[0]**2 + qG[1]**2 + qG[2]**2)

def RPA_susceptibility(eta_qG, N_kpairs, V_cell):
    """
    Calculates the Kohn-Sham susceptibility chi^0_{GGp}(q,E) for all E

    Inputs:
        eta_qG:     np.ndarray of shape (N_kpairs, N_valbands, N_conbands): All 3D overlaps for q+G generated by get_3D_overlaps
        N_kpairs:   int: number of k'-k pairs corresponding to q
        V_cell:     float: volume of unit cell in units of bohr^3

    Outputs:
        chi:        np.ndarray of shape (N_enegies,): Kohn-Sham susceptibility, Eq.() 
    """
    re_delE = np.load(parmt.store+'/re_delE.npy') #Real part of 1/(E - (E_jk'-E_ik) + in)
    im_delE = np.load(parmt.store+'/im_delE.npy') #Imaginary part of 1/(E - (E_jk'-E_ik) + in)

    chi_num = np.abs(eta_qG)**2
    chi = chi_num[:,:,:,None] * (re_delE + 1j*im_delE) #(k_pair,i,j,E)
    return 2/N_kpairs/V_cell * chi.sum(axis=(0,1,2)) #divide by number of k pairs and cell volume (move to later step later). Factor of 2 is from occupation

def RPA_dielectric(G, q, k_f, mo_coeff_i, mo_coeff_f_conj, unique_Ri, blocks, N_AO, q_cuts, N_kpairs, V_cell):
    """
    Calculates epsilon_{GG}(q, E) for all energies E at single 1BZ q-vector + G-vector. Does not include local field effects.

    Inputs:
        G:          np.ndarray of shape (3,): G-vector
        q:          np.ndarray of shape (3,): 1BZ q-vector
        k_f:        np.ndarray of shape (N_kpairs, 3): k' corresponding to q
        mo_coeff_i: np.ndarray of shape (N_kpairs, N_AO, N_valbands)
        mo_coeff_f: np.ndarray of shape (N_kpairs, N_AO, N_conbands)
        R_unique:   list of unique R scalars in each dimension
        blocks:     dict: atomic orbital blocks generated by get_basis_blocks
        N_AO:       int: number of atomic orbitals
        q_cuts:     np.ndarray of shape (N_q, ) where each element corresponds to the magnitude of the q vector at which the R_ids change.
        N_kpairs:   int: number of k'-k pairs corresponding to q
        V_cell:     float: volume of unit cell in units of bohr^3
    Outputs:
        eps:        np.ndarray of shape (N_energies,): epsilon_{GG}(q,E) 
    """
    eta_qG = get_3D_overlaps_blocks(q+G, k_f, blocks, N_AO, mo_coeff_i, mo_coeff_f_conj, unique_Ri, q_cuts)

    eps = 1 - (4*np.pi*alpha)**2 * me / np.linalg.norm(q+G)**2 * RPA_susceptibility(eta_qG, N_kpairs, V_cell)
    return eps

def RPA_dielectric_lfe(q, G_vectors, k_pairs, mo_en_i, mo_en_f, eta_q):
    """
    To Do:
    - This whole function needs to be restructured, may move to separate file in future
    - Fix np.diag in last step
    - Update for multiprocessing: only take one G, Gp pair

    Calculates epsilon_{GG}(q, E) for all energies E and G-vectors G at single 1BZ q-vector. Includes local field effects by calculating eps_{GGp}(q,E), then inverting and taking diagonal elements. This cannot be done for large q_max: |q+G| < ~5ame advised.

    Inputs:
        q:          np.ndarray of shape (3,): 1BZ q-vector
        G_vectors:
        k_pairs:
        mo_en_i:
        mo_en_f:
        eta_q:      np.ndarray: all 3D overlaps for q generated by get_3D_overlaps
    Outputs:
        eps:        np.array of shape (N_energies,N_G_vectors): epsilon_{GG}(q,E) 
    """
    num_G = G_vectors.shape[0]
    E = np.arange(0, parmt.E_max+parmt.dE, parmt.dE)
    eps_matrix = np.zeros((E.shape[0], num_G, num_G))
    eps_lfe = np.zeros(E.shape[0], num_G) #(E,G)

    for G_id, G in enumerate(G_vectors):
        for Gp_id, Gp in enumerate(G_vectors):
            eps_matrix[:,G_id,Gp_id] = -(4*np.pi)**2 / np.linalg.norm(q+G) / np.linalg.norm(q+Gp) * RPA_susceptibility(E, G_id, G_id, k_pairs, mo_en_i, mo_en_f, eta_q)
    eps_matrix = eps_matrix + np.identity(num_G)
    eps_lfe = 1/np.diag(np.linalg.inv(eps_matrix)) #need to fix: np.diag does not work with non-2d matrix
    return eps_lfe

@njit()
def kramerskronig_im2re(im, dE = parmt.dE, E_max=parmt.E_max):
    """
    Computes the Kramers-Kronig transformation of the input imaginary part to obtain the real part.

    Input:
        im: np.ndarray (N_E, N_G)
    Output:
        re: np.ndarray (N_E, N_G), Note that Re(eps) = eps_re + 1 
    """
    E = np.arange(0, E_max+dE, dE)
    re = np.empty_like(im)
    N_G, N_E = im.shape
    for nE in range(N_E):
        E_pv = np.delete(E, nE) #removes Ei = En for principal value
        En = E[nE]
        for nG in range(N_G):
            im_pv = np.concatenate((im[nG, :nE], im[nG, nE+1:]))

            s = 0
            for ns in range(N_E-1):
                s += E_pv[ns]*im_pv[ns]/(E_pv[ns]**2 - En**2)

            re[nG,nE] = 2/np.pi*dE*(s - 0.5*(E_pv[0]*im_pv[0]/(E_pv[0]**2-En**2) + E_pv[-1]*im_pv[-1]/(E_pv[-1]**2-En**2))) #trapezoid rule
    return re

@njit()
def kramerskronig_re2im(re, dE = parmt.dE, E_max=parmt.E_max):
    """
    Computes the Kramers-Kronig transformation of the input real part to obtain the imaginary part.

    Input:
        re: np.ndarray (N_E, N_G)
    Output:
        im: np.ndarray (N_E, N_G)
    """
    E = np.arange(0, E_max+dE, dE)
    im = np.empty_like(re)
    N_G, N_E = re.shape
    for nE in range(N_E):
        E_pv = np.delete(E, nE) #removes Ei = En for principal value
        En = E[nE]
        for nG in range(N_G):
            re_pv = np.concatenate((re[nG, :nE], re[nG, nE+1:]))

            s = 0
            for ns in range(N_E-1):
                s += re_pv[ns]/(E_pv[ns]**2 - En**2)

            im[nG,nE] = -2/np.pi*dE*En*(s - 0.5*(re_pv[0]/(E_pv[0]**2-En**2) + re_pv[-1]/(E_pv[-1]**2-En**2))) #trapezoid rule
    return im